package com.example.todo.controller;

import com.example.todo.model.Todo;
import com.example.todo.repository.TodoRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import java.util.List;
import java.util.Optional;

import static org.hamcrest.Matchers.containsString;
import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest
@AutoConfigureMockMvc
public class TodoControllerIntegrationTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private TodoRepository todoRepository;

    private Todo task1;

    @BeforeEach
    void setUp() {
        // Clean up before each test to ensure isolation
        todoRepository.deleteAll();

        // Setup initial data if needed by multiple tests, otherwise create in test methods
        task1 = new Todo();
        task1.setTitle("Initial Task for Tests");
        task1.setCompleted(false);
        // ID will be generated by DB
    }

    @AfterEach
    void tearDown() {
        todoRepository.deleteAll();
    }

    @Test
    void testGetIndex_shouldShowTask() throws Exception {
        Todo savedTask = todoRepository.save(new Todo(0L, "Test Get Index", false));

        mockMvc.perform(get("/"))
                .andExpect(status().isOk())
                .andExpect(view().name("index"))
                .andExpect(content().string(containsString("Test Get Index")));
    }

    @Test
    void testPostAdd_shouldCreateTaskAndRedirect() throws Exception {
        mockMvc.perform(post("/add")
                        .contentType(MediaType.APPLICATION_FORM_URLENCODED)
                        .param("title", "New Task via POST"))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/"));

        List<Todo> todos = todoRepository.findAll();
        assertEquals(1, todos.size());
        assertEquals("New Task via POST", todos.get(0).getTitle());
    }

    @Test
    void testPostDelete_shouldRemoveTaskAndRedirect() throws Exception {
        Todo taskToDelete = todoRepository.save(new Todo(0L, "Task to Delete", false));
        Long taskId = taskToDelete.getId();

        mockMvc.perform(post("/delete")
                        .contentType(MediaType.APPLICATION_FORM_URLENCODED)
                        .param("id", String.valueOf(taskId)))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/"));

        Optional<Todo> deletedTask = todoRepository.findById(taskId);
        assertFalse(deletedTask.isPresent());
    }

    @Test
    void testPostComplete_shouldMarkTaskAsCompletedAndRedirect() throws Exception {
        Todo taskToComplete = todoRepository.save(new Todo(0L, "Task to Complete", false));
        Long taskId = taskToComplete.getId();

        mockMvc.perform(post("/complete")
                        .contentType(MediaType.APPLICATION_FORM_URLENCODED)
                        .param("id", String.valueOf(taskId)))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/"));

        Optional<Todo> completedTaskOptional = todoRepository.findById(taskId);
        assertTrue(completedTaskOptional.isPresent());
        assertTrue(completedTaskOptional.get().isCompleted());
    }

    @Test
    void testGetEditId_shouldShowEditFormWithTaskDetails() throws Exception {
        Todo taskToEdit = todoRepository.save(new Todo(0L, "Task to Edit", false));
        Long taskId = taskToEdit.getId();

        mockMvc.perform(get("/edit/" + taskId))
                .andExpect(status().isOk())
                .andExpect(view().name("edit-todo"))
                .andExpect(content().string(containsString("Task to Edit")))
                .andExpect(xpath("//input[@name='title']/@value").string("Task to Edit"));
    }

    @Test
    void testGetEditId_shouldRedirectIfNotFound() throws Exception {
        mockMvc.perform(get("/edit/999")) // Assuming ID 999 does not exist
            .andExpect(status().is3xxRedirection())
            .andExpect(redirectedUrl("/"));
    }


    @Test
    void testPostUpdateId_shouldUpdateTaskAndRedirect() throws Exception {
        Todo taskToUpdate = todoRepository.save(new Todo(0L, "Original Title", false));
        Long taskId = taskToUpdate.getId();

        mockMvc.perform(post("/update/" + taskId)
                        .contentType(MediaType.APPLICATION_FORM_URLENCODED)
                        .param("title", "Updated Title via POST"))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/"));

        Optional<Todo> updatedTaskOptional = todoRepository.findById(taskId);
        assertTrue(updatedTaskOptional.isPresent());
        assertEquals("Updated Title via POST", updatedTaskOptional.get().getTitle());
    }

    @Test
    void testPostUpdateId_shouldNotUpdateIfTitleIsEmptyAndRedirect() throws Exception {
        Todo taskToUpdate = todoRepository.save(new Todo(0L, "Original Title", false));
        Long taskId = taskToUpdate.getId();

        mockMvc.perform(post("/update/" + taskId)
                        .contentType(MediaType.APPLICATION_FORM_URLENCODED)
                        .param("title", "  ")) // Empty title
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/"));

        Optional<Todo> taskAfterUpdate = todoRepository.findById(taskId);
        assertTrue(taskAfterUpdate.isPresent());
        assertEquals("Original Title", taskAfterUpdate.get().getTitle()); // Title should not change
    }

}
