package com.example.todo.controller;

import com.example.todo.model.Priority;
import com.example.todo.model.Todo;
import com.example.todo.repository.TodoRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.util.LinkedMultiValueMap;
import org.springframework.util.MultiValueMap;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Optional;

import static org.hamcrest.Matchers.containsString;
import static org.hamcrest.Matchers.not;
import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest
@AutoConfigureMockMvc
public class TodoControllerIntegrationTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private TodoRepository todoRepository;

    private Todo task1;

    @BeforeEach
    void setUp() {
        // Clean up before each test to ensure isolation
        todoRepository.deleteAll();

        // Setup initial data if needed by multiple tests, otherwise create in test methods
        task1 = new Todo();
        task1.setTitle("Initial Task for Tests");
        task1.setCompleted(false);
        // ID will be generated by DB
    }

    @AfterEach
    void tearDown() {
        todoRepository.deleteAll();
    }

    @Test
    void testGetIndex_shouldShowTask() throws Exception {
        Todo savedTask = todoRepository.save(new Todo(0L, "Test Get Index", false, null, null)); // Added null for dueDate and priority

        mockMvc.perform(get("/"))
                .andExpect(status().isOk())
                .andExpect(view().name("index"))
                .andExpect(content().string(containsString("Test Get Index")));
    }

    @Test
    void testPostAdd_shouldCreateTaskAndRedirect() throws Exception {
        LocalDate dueDate = LocalDate.now().plusDays(3);
        String formattedDueDate = dueDate.format(DateTimeFormatter.ISO_DATE);
        Priority priority = Priority.HIGH;

        MultiValueMap<String, String> params = new LinkedMultiValueMap<>();
        params.add("title", "New Task via POST");
        params.add("dueDate", formattedDueDate);
        params.add("priority", priority.name());

        mockMvc.perform(post("/add")
                        .contentType(MediaType.APPLICATION_FORM_URLENCODED)
                        .params(params))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/"));

        List<Todo> todos = todoRepository.findAll();
        assertEquals(1, todos.size());
        assertEquals("New Task via POST", todos.get(0).getTitle());
        assertEquals(dueDate, todos.get(0).getDueDate());
        assertEquals(priority, todos.get(0).getPriority());
    }

    @Test
    void testPostAdd_withNoPriority_shouldDefaultToMedium() throws Exception {
        LocalDate dueDate = LocalDate.now().plusDays(3);
        String formattedDueDate = dueDate.format(DateTimeFormatter.ISO_DATE);

        MultiValueMap<String, String> params = new LinkedMultiValueMap<>();
        params.add("title", "Task with Default Priority");
        params.add("dueDate", formattedDueDate);
        // No priority parameter sent

        mockMvc.perform(post("/add")
                        .contentType(MediaType.APPLICATION_FORM_URLENCODED)
                        .params(params))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/"));

        List<Todo> todos = todoRepository.findAll();
        assertEquals(1, todos.size());
        assertEquals("Task with Default Priority", todos.get(0).getTitle());
        assertEquals(Priority.MEDIUM, todos.get(0).getPriority()); // Assuming MEDIUM is default
    }

    @Test
    void testPostDelete_shouldRemoveTaskAndRedirect() throws Exception {
        Todo taskToDelete = todoRepository.save(new Todo(0L, "Task to Delete", false, null, null)); // Added null for dueDate and priority
        Long taskId = taskToDelete.getId();

        mockMvc.perform(post("/delete")
                        .contentType(MediaType.APPLICATION_FORM_URLENCODED)
                        .param("id", String.valueOf(taskId)))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/"));

        Optional<Todo> deletedTask = todoRepository.findById(taskId);
        assertFalse(deletedTask.isPresent());
    }

    @Test
    void testPostComplete_shouldMarkTaskAsCompletedAndRedirect() throws Exception {
        Todo taskToComplete = todoRepository.save(new Todo(0L, "Task to Complete", false, null, null)); // Added null for dueDate and priority
        Long taskId = taskToComplete.getId();

        mockMvc.perform(post("/complete")
                        .contentType(MediaType.APPLICATION_FORM_URLENCODED)
                        .param("id", String.valueOf(taskId)))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/"));

        Optional<Todo> completedTaskOptional = todoRepository.findById(taskId);
        assertTrue(completedTaskOptional.isPresent());
        assertTrue(completedTaskOptional.get().isCompleted());
    }

    @Test
    void testGetEditId_shouldShowEditFormWithTaskDetails() throws Exception {
        LocalDate dueDate = LocalDate.now().plusDays(5);
        String formattedDueDate = dueDate.format(DateTimeFormatter.ISO_DATE);
        Priority priority = Priority.HIGH;
        Todo taskToEdit = new Todo(0L, "Task to Edit", false, dueDate, priority);
        taskToEdit = todoRepository.save(taskToEdit);
        Long taskId = taskToEdit.getId();

        mockMvc.perform(get("/edit/" + taskId))
                .andExpect(status().isOk())
                .andExpect(view().name("edit-todo"))
                .andExpect(content().string(containsString("Task to Edit")))
                .andExpect(xpath("//input[@name='title']/@value").string("Task to Edit"))
                .andExpect(xpath("//input[@name='dueDate']/@value").string(formattedDueDate))
                .andExpect(xpath("//select[@name='priority']/option[@value='HIGH' and @selected='selected']").exists())
                .andExpect(xpath("//select[@name='priority']/option[@value='MEDIUM']").exists())
                .andExpect(xpath("//select[@name='priority']/option[@value='LOW']").exists());
    }

    @Test
    void testGetEditId_shouldRedirectIfNotFound() throws Exception {
        mockMvc.perform(get("/edit/999")) // Assuming ID 999 does not exist
            .andExpect(status().is3xxRedirection())
            .andExpect(redirectedUrl("/"));
    }


    @Test
    void testPostUpdateId_shouldUpdateTaskAndRedirect() throws Exception {
        LocalDate initialDueDate = LocalDate.now().plusDays(2);
        Priority initialPriority = Priority.LOW;
        Todo taskToUpdate = new Todo(0L, "Original Title", false, initialDueDate, initialPriority);
        taskToUpdate = todoRepository.save(taskToUpdate);
        Long taskId = taskToUpdate.getId();

        LocalDate newDueDate = LocalDate.now().plusDays(7);
        String formattedNewDueDate = newDueDate.format(DateTimeFormatter.ISO_DATE);
        Priority newPriority = Priority.HIGH;

        MultiValueMap<String, String> params = new LinkedMultiValueMap<>();
        params.add("title", "Updated Title via POST");
        params.add("dueDate", formattedNewDueDate);
        params.add("priority", newPriority.name());

        mockMvc.perform(post("/update/" + taskId)
                        .contentType(MediaType.APPLICATION_FORM_URLENCODED)
                        .params(params))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/"));

        Optional<Todo> updatedTaskOptional = todoRepository.findById(taskId);
        assertTrue(updatedTaskOptional.isPresent());
        assertEquals("Updated Title via POST", updatedTaskOptional.get().getTitle());
        assertEquals(newDueDate, updatedTaskOptional.get().getDueDate());
        assertEquals(newPriority, updatedTaskOptional.get().getPriority());
    }

    @Test
    void testPostUpdateId_withNoPriority_shouldRetainExistingPriority() throws Exception {
        LocalDate initialDueDate = LocalDate.now().plusDays(2);
        Priority initialPriority = Priority.HIGH;
        Todo taskToUpdate = new Todo(0L, "Original Title", false, initialDueDate, initialPriority);
        taskToUpdate = todoRepository.save(taskToUpdate);
        Long taskId = taskToUpdate.getId();

        String formattedNewDueDate = LocalDate.now().plusDays(5).format(DateTimeFormatter.ISO_DATE);
        MultiValueMap<String, String> params = new LinkedMultiValueMap<>();
        params.add("title", "Updated Title Only");
        params.add("dueDate", formattedNewDueDate);
        // No priority parameter sent

        mockMvc.perform(post("/update/" + taskId)
                        .contentType(MediaType.APPLICATION_FORM_URLENCODED)
                        .params(params))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/"));

        Optional<Todo> taskAfterUpdate = todoRepository.findById(taskId);
        assertTrue(taskAfterUpdate.isPresent());
        assertEquals("Updated Title Only", taskAfterUpdate.get().getTitle());
        assertEquals(initialPriority, taskAfterUpdate.get().getPriority()); // Priority should remain unchanged
    }

    @Test
    void testPostUpdateId_shouldNotUpdateIfTitleIsEmptyAndRedirect() throws Exception {
        LocalDate initialDueDate = LocalDate.now().plusDays(2);
        Priority initialPriority = Priority.MEDIUM;
        Todo taskToUpdate = new Todo(0L, "Original Title", false, initialDueDate, initialPriority);
        taskToUpdate = todoRepository.save(taskToUpdate);
        Long taskId = taskToUpdate.getId();

        String formattedNewDueDate = LocalDate.now().plusDays(5).format(DateTimeFormatter.ISO_DATE);

        MultiValueMap<String, String> params = new LinkedMultiValueMap<>();
        params.add("title", "  "); // Empty title
        params.add("dueDate", formattedNewDueDate);
        params.add("priority", Priority.HIGH.name());


        mockMvc.perform(post("/update/" + taskId)
                        .contentType(MediaType.APPLICATION_FORM_URLENCODED)
                        .params(params))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/"));

        Optional<Todo> taskAfterUpdate = todoRepository.findById(taskId);
        assertTrue(taskAfterUpdate.isPresent());
        assertEquals("Original Title", taskAfterUpdate.get().getTitle()); // Title should not change
        assertEquals(initialDueDate, taskAfterUpdate.get().getDueDate()); // Due date should also not change
        assertEquals(initialPriority, taskAfterUpdate.get().getPriority()); // Priority should also not change
    }

    @Test
    void testGetIndex_shouldDisplayDueDateAndHighlightOverdueTasksAndPriority() throws Exception {
        LocalDate today = LocalDate.now();
        Todo overdueTask = new Todo(0L, "Overdue Task", false, today.minusDays(1), Priority.HIGH);
        Todo upcomingTask = new Todo(0L, "Upcoming Task", false, today.plusDays(2), Priority.LOW);
        todoRepository.save(overdueTask);
        todoRepository.save(upcomingTask);

        mockMvc.perform(get("/"))
                .andExpect(status().isOk())
                .andExpect(view().name("index"))
                .andExpect(content().string(containsString("Overdue Task")))
                .andExpect(content().string(containsString("task-overdue")))
                .andExpect(xpath("//li[contains(.,'Overdue Task')]//span[contains(@class, 'badge-danger') and text()='High']").exists())
                .andExpect(content().string(containsString("Upcoming Task")))
                .andExpect(xpath("//li[contains(.,'Upcoming Task') and not(contains(@class, 'task-overdue'))]").exists())
                .andExpect(xpath("//li[contains(.,'Upcoming Task')]//span[contains(@class, 'badge-info') and text()='Low']").exists());
    }
}
